# Generated by Django 2.2.2 on 2019-10-27 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mickys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
